host-record=puppetmaster1.puppetlab.com,puppetmaster1,10.0.1.10
host-record=puppetmaster2.puppetlab.com,puppetmaster2,10.0.1.20
host-record=puppetmaster3.puppetlab.com,puppetmaster3,10.0.1.30
host-record=puppetca1.puppetlab.com,puppetca1,10.0.1.40
host-record=puppetca2.puppetlab.com,puppetca2,10.1.0.50
host-record=admin.puppetlab.com,admin,10.1.0.60
host-record=worker1.puppetlab.com,worker1,10.1.0.70
host-record=worker2.puppetlab.com,worker2,10.1.0.80
host-record=worker3.puppetlab.com,worker3,10.1.0.90
server=10.0.0.2
no-resolv
